// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: git.underland.io/ehazlett/finca/api/services/render/v1/render.proto

package render

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueueJobRequest struct {
	// Types that are valid to be assigned to Data:
	//	*QueueJobRequest_Request
	//	*QueueJobRequest_ChunkData
	Data                 isQueueJobRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QueueJobRequest) Reset()         { *m = QueueJobRequest{} }
func (m *QueueJobRequest) String() string { return proto.CompactTextString(m) }
func (*QueueJobRequest) ProtoMessage()    {}
func (*QueueJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa69ac579737354, []int{0}
}
func (m *QueueJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueJobRequest.Unmarshal(m, b)
}
func (m *QueueJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueJobRequest.Marshal(b, m, deterministic)
}
func (m *QueueJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueJobRequest.Merge(m, src)
}
func (m *QueueJobRequest) XXX_Size() int {
	return xxx_messageInfo_QueueJobRequest.Size(m)
}
func (m *QueueJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueJobRequest proto.InternalMessageInfo

type isQueueJobRequest_Data interface {
	isQueueJobRequest_Data()
}

type QueueJobRequest_Request struct {
	Request *JobRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"`
}
type QueueJobRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof" json:"chunk_data,omitempty"`
}

func (*QueueJobRequest_Request) isQueueJobRequest_Data()   {}
func (*QueueJobRequest_ChunkData) isQueueJobRequest_Data() {}

func (m *QueueJobRequest) GetData() isQueueJobRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueueJobRequest) GetRequest() *JobRequest {
	if x, ok := m.GetData().(*QueueJobRequest_Request); ok {
		return x.Request
	}
	return nil
}

func (m *QueueJobRequest) GetChunkData() []byte {
	if x, ok := m.GetData().(*QueueJobRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueueJobRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueueJobRequest_Request)(nil),
		(*QueueJobRequest_ChunkData)(nil),
	}
}

type JobRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResolutionX          int64    `protobuf:"varint,3,opt,name=resolution_x,json=resolutionX,proto3" json:"resolution_x,omitempty"`
	ResolutionY          int64    `protobuf:"varint,4,opt,name=resolution_y,json=resolutionY,proto3" json:"resolution_y,omitempty"`
	ResolutionScale      int64    `protobuf:"varint,5,opt,name=resolution_scale,json=resolutionScale,proto3" json:"resolution_scale,omitempty"`
	RenderSamples        int64    `protobuf:"varint,6,opt,name=render_samples,json=renderSamples,proto3" json:"render_samples,omitempty"`
	RenderStartFrame     int64    `protobuf:"varint,7,opt,name=render_start_frame,json=renderStartFrame,proto3" json:"render_start_frame,omitempty"`
	RenderEndFrame       int64    `protobuf:"varint,8,opt,name=render_end_frame,json=renderEndFrame,proto3" json:"render_end_frame,omitempty"`
	RenderUseGPU         bool     `protobuf:"varint,9,opt,name=render_use_gpu,json=renderUseGpu,proto3" json:"render_use_gpu,omitempty"`
	RenderPriority       int64    `protobuf:"varint,10,opt,name=render_priority,json=renderPriority,proto3" json:"render_priority,omitempty"`
	CPU                  int64    `protobuf:"varint,11,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               int64    `protobuf:"varint,12,opt,name=memory,proto3" json:"memory,omitempty"`
	RenderSlices         int64    `protobuf:"varint,13,opt,name=render_slices,json=renderSlices,proto3" json:"render_slices,omitempty"`
	ContentType          string   `protobuf:"bytes,14,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa69ac579737354, []int{1}
}
func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *JobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobRequest) GetResolutionX() int64 {
	if m != nil {
		return m.ResolutionX
	}
	return 0
}

func (m *JobRequest) GetResolutionY() int64 {
	if m != nil {
		return m.ResolutionY
	}
	return 0
}

func (m *JobRequest) GetResolutionScale() int64 {
	if m != nil {
		return m.ResolutionScale
	}
	return 0
}

func (m *JobRequest) GetRenderSamples() int64 {
	if m != nil {
		return m.RenderSamples
	}
	return 0
}

func (m *JobRequest) GetRenderStartFrame() int64 {
	if m != nil {
		return m.RenderStartFrame
	}
	return 0
}

func (m *JobRequest) GetRenderEndFrame() int64 {
	if m != nil {
		return m.RenderEndFrame
	}
	return 0
}

func (m *JobRequest) GetRenderUseGPU() bool {
	if m != nil {
		return m.RenderUseGPU
	}
	return false
}

func (m *JobRequest) GetRenderPriority() int64 {
	if m != nil {
		return m.RenderPriority
	}
	return 0
}

func (m *JobRequest) GetCPU() int64 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *JobRequest) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *JobRequest) GetRenderSlices() int64 {
	if m != nil {
		return m.RenderSlices
	}
	return 0
}

func (m *JobRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type QueueJobResponse struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueJobResponse) Reset()         { *m = QueueJobResponse{} }
func (m *QueueJobResponse) String() string { return proto.CompactTextString(m) }
func (*QueueJobResponse) ProtoMessage()    {}
func (*QueueJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa69ac579737354, []int{2}
}
func (m *QueueJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueJobResponse.Unmarshal(m, b)
}
func (m *QueueJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueJobResponse.Marshal(b, m, deterministic)
}
func (m *QueueJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueJobResponse.Merge(m, src)
}
func (m *QueueJobResponse) XXX_Size() int {
	return xxx_messageInfo_QueueJobResponse.Size(m)
}
func (m *QueueJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueJobResponse proto.InternalMessageInfo

func (m *QueueJobResponse) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type Job struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa69ac579737354, []int{3}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

type ListJobsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsRequest) Reset()         { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()    {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa69ac579737354, []int{4}
}
func (m *ListJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRequest.Unmarshal(m, b)
}
func (m *ListJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRequest.Marshal(b, m, deterministic)
}
func (m *ListJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRequest.Merge(m, src)
}
func (m *ListJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListJobsRequest.Size(m)
}
func (m *ListJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRequest proto.InternalMessageInfo

type ListJobsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsResponse) Reset()         { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()    {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa69ac579737354, []int{5}
}
func (m *ListJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsResponse.Unmarshal(m, b)
}
func (m *ListJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsResponse.Marshal(b, m, deterministic)
}
func (m *ListJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsResponse.Merge(m, src)
}
func (m *ListJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobsResponse.Size(m)
}
func (m *ListJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueueJobRequest)(nil), "finca.services.render.v1.QueueJobRequest")
	proto.RegisterType((*JobRequest)(nil), "finca.services.render.v1.JobRequest")
	proto.RegisterType((*QueueJobResponse)(nil), "finca.services.render.v1.QueueJobResponse")
	proto.RegisterType((*Job)(nil), "finca.services.render.v1.Job")
	proto.RegisterType((*ListJobsRequest)(nil), "finca.services.render.v1.ListJobsRequest")
	proto.RegisterType((*ListJobsResponse)(nil), "finca.services.render.v1.ListJobsResponse")
}

func init() {
	proto.RegisterFile("git.underland.io/ehazlett/finca/api/services/render/v1/render.proto", fileDescriptor_faa69ac579737354)
}

var fileDescriptor_faa69ac579737354 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x17, 0xda, 0x75, 0xed, 0x69, 0xb7, 0x16, 0x0b, 0x21, 0x33, 0x90, 0x5a, 0x0a, 0x88,
	0x0e, 0xa1, 0x84, 0x0d, 0x89, 0x1b, 0x84, 0x40, 0xdd, 0x80, 0x31, 0x71, 0x31, 0x32, 0x2a, 0x0d,
	0x6e, 0x22, 0x37, 0x3d, 0xeb, 0x22, 0xd2, 0x38, 0xf8, 0xcf, 0x44, 0x10, 0x4f, 0xc0, 0xd3, 0xf1,
	0x04, 0xbb, 0xd8, 0x93, 0xa0, 0x38, 0xce, 0x3a, 0x55, 0x5a, 0x85, 0xb8, 0x3b, 0xfe, 0xce, 0xef,
	0xf8, 0x3b, 0x8e, 0x4f, 0x0c, 0xbb, 0xd3, 0x48, 0xb9, 0x3a, 0x99, 0xa0, 0x88, 0x59, 0x32, 0x71,
	0x23, 0xee, 0xe1, 0x29, 0xfb, 0x19, 0xa3, 0x52, 0xde, 0x49, 0x94, 0x84, 0xcc, 0x63, 0x69, 0xe4,
	0x49, 0x14, 0x67, 0x51, 0x88, 0xd2, 0x13, 0x98, 0x93, 0xde, 0xd9, 0xb6, 0x8d, 0xdc, 0x54, 0x70,
	0xc5, 0x09, 0x35, 0xa8, 0x5b, 0x62, 0xae, 0x4d, 0x9e, 0x6d, 0x6f, 0xde, 0x9a, 0xf2, 0x29, 0x37,
	0x90, 0x97, 0x47, 0x05, 0xbf, 0x79, 0x77, 0xca, 0xf9, 0x34, 0x46, 0xcf, 0xac, 0xc6, 0xfa, 0xc4,
	0xc3, 0x59, 0xaa, 0xb2, 0x22, 0xd9, 0xff, 0x05, 0xed, 0x4f, 0x1a, 0x35, 0x1e, 0xf0, 0xb1, 0x8f,
	0xdf, 0x35, 0x4a, 0x45, 0xde, 0xc0, 0x9a, 0x28, 0x42, 0xea, 0xf4, 0x9c, 0x41, 0x73, 0xe7, 0xa1,
	0x7b, 0x9d, 0xa3, 0x3b, 0x2f, 0xdb, 0x5f, 0xf1, 0xcb, 0x32, 0xd2, 0x05, 0x08, 0x4f, 0x75, 0xf2,
	0x2d, 0x98, 0x30, 0xc5, 0xe8, 0x8d, 0x9e, 0x33, 0x68, 0xed, 0xaf, 0xf8, 0x0d, 0xa3, 0xed, 0x31,
	0xc5, 0x86, 0x35, 0xa8, 0xe6, 0xa9, 0xfe, 0xef, 0x2a, 0xc0, 0x15, 0xe7, 0x7b, 0x50, 0xd5, 0x3a,
	0x9a, 0x18, 0xdb, 0xc6, 0xb0, 0x7e, 0x71, 0xde, 0xad, 0x8e, 0x46, 0x1f, 0xf6, 0x7c, 0xa3, 0x12,
	0x02, 0xd5, 0x84, 0xcd, 0xd0, 0xec, 0xd7, 0xf0, 0x4d, 0x4c, 0xee, 0x43, 0x4b, 0xa0, 0xe4, 0xb1,
	0x56, 0x11, 0x4f, 0x82, 0x1f, 0xb4, 0xd2, 0x73, 0x06, 0x15, 0xbf, 0x39, 0xd7, 0x8e, 0x17, 0x90,
	0x8c, 0x56, 0x17, 0x91, 0x2f, 0x64, 0x0b, 0x3a, 0x57, 0x10, 0x19, 0xb2, 0x18, 0xe9, 0xaa, 0xc1,
	0xda, 0x73, 0xfd, 0x28, 0x97, 0xc9, 0x23, 0xd8, 0x28, 0x4e, 0x1f, 0x48, 0x36, 0x4b, 0x63, 0x94,
	0xb4, 0x66, 0xc0, 0xf5, 0x42, 0x3d, 0x2a, 0x44, 0xf2, 0x14, 0x48, 0x89, 0x29, 0x26, 0x54, 0x70,
	0x22, 0xf2, 0xce, 0xd7, 0x0c, 0xda, 0xb1, 0x68, 0x9e, 0x78, 0x97, 0xeb, 0x64, 0x00, 0x56, 0x0b,
	0x30, 0x99, 0x58, 0xb6, 0x6e, 0x58, 0x6b, 0xf6, 0x36, 0x99, 0x14, 0xe4, 0x8b, 0x4b, 0x7b, 0x2d,
	0x31, 0x98, 0xa6, 0x9a, 0x36, 0x7a, 0xce, 0xa0, 0x3e, 0xec, 0x5c, 0x9c, 0x77, 0x5b, 0xbe, 0xc9,
	0x8c, 0x24, 0xbe, 0x3f, 0x1c, 0xf9, 0x2d, 0x71, 0xb9, 0x4a, 0x35, 0x79, 0x0c, 0x6d, 0x5b, 0x97,
	0x8a, 0x88, 0x8b, 0x48, 0x65, 0x14, 0xae, 0x1a, 0x1c, 0x5a, 0x95, 0xdc, 0x81, 0x4a, 0x98, 0x6a,
	0xda, 0xcc, 0x93, 0xc3, 0xb5, 0x8b, 0xf3, 0x6e, 0x65, 0xf7, 0x70, 0xe4, 0xe7, 0x1a, 0xb9, 0x0d,
	0xb5, 0x19, 0xce, 0xb8, 0xc8, 0x68, 0xcb, 0x94, 0xda, 0x15, 0x79, 0x00, 0xeb, 0xe5, 0x59, 0xe3,
	0x7c, 0x3c, 0xe8, 0xba, 0x49, 0xdb, 0x06, 0x8e, 0x8c, 0x96, 0xdf, 0x42, 0xc8, 0x13, 0x85, 0x89,
	0x0a, 0x54, 0x96, 0x22, 0xdd, 0x30, 0x97, 0xd8, 0xb4, 0xda, 0xe7, 0x2c, 0xc5, 0xfe, 0x33, 0xe8,
	0xcc, 0x47, 0x51, 0xa6, 0x3c, 0x91, 0xb8, 0x7c, 0x22, 0xfa, 0xab, 0x50, 0x39, 0xe0, 0xe3, 0xfe,
	0x4d, 0x68, 0x7f, 0x8c, 0xa4, 0x3a, 0xe0, 0x63, 0x69, 0x27, 0xa9, 0x4f, 0xa0, 0x33, 0x97, 0x8a,
	0xbd, 0x76, 0xfe, 0x38, 0x50, 0x2b, 0x3e, 0x11, 0x09, 0xa1, 0x5e, 0x5a, 0x91, 0xad, 0xeb, 0xa7,
	0x7b, 0xe1, 0xcf, 0xd8, 0x7c, 0xf2, 0x2f, 0x68, 0xe1, 0x36, 0x70, 0x08, 0x83, 0x7a, 0xd9, 0xc3,
	0x32, 0x93, 0x85, 0xd6, 0x97, 0x99, 0x2c, 0x1e, 0x69, 0xf8, 0xfa, 0xeb, 0xab, 0xff, 0x7b, 0x51,
	0x5e, 0x16, 0xd1, 0xb1, 0x33, 0xae, 0x99, 0x77, 0xe0, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0x88, 0xf7, 0x0d, 0x9b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RenderClient is the client API for Render service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RenderClient interface {
	QueueJob(ctx context.Context, opts ...grpc.CallOption) (Render_QueueJobClient, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
}

type renderClient struct {
	cc *grpc.ClientConn
}

func NewRenderClient(cc *grpc.ClientConn) RenderClient {
	return &renderClient{cc}
}

func (c *renderClient) QueueJob(ctx context.Context, opts ...grpc.CallOption) (Render_QueueJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Render_serviceDesc.Streams[0], "/finca.services.render.v1.Render/QueueJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &renderQueueJobClient{stream}
	return x, nil
}

type Render_QueueJobClient interface {
	Send(*QueueJobRequest) error
	CloseAndRecv() (*QueueJobResponse, error)
	grpc.ClientStream
}

type renderQueueJobClient struct {
	grpc.ClientStream
}

func (x *renderQueueJobClient) Send(m *QueueJobRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *renderQueueJobClient) CloseAndRecv() (*QueueJobResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(QueueJobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *renderClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/finca.services.render.v1.Render/ListJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenderServer is the server API for Render service.
type RenderServer interface {
	QueueJob(Render_QueueJobServer) error
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
}

// UnimplementedRenderServer can be embedded to have forward compatible implementations.
type UnimplementedRenderServer struct {
}

func (*UnimplementedRenderServer) QueueJob(srv Render_QueueJobServer) error {
	return status.Errorf(codes.Unimplemented, "method QueueJob not implemented")
}
func (*UnimplementedRenderServer) ListJobs(ctx context.Context, req *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}

func RegisterRenderServer(s *grpc.Server, srv RenderServer) {
	s.RegisterService(&_Render_serviceDesc, srv)
}

func _Render_QueueJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RenderServer).QueueJob(&renderQueueJobServer{stream})
}

type Render_QueueJobServer interface {
	SendAndClose(*QueueJobResponse) error
	Recv() (*QueueJobRequest, error)
	grpc.ServerStream
}

type renderQueueJobServer struct {
	grpc.ServerStream
}

func (x *renderQueueJobServer) SendAndClose(m *QueueJobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *renderQueueJobServer) Recv() (*QueueJobRequest, error) {
	m := new(QueueJobRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Render_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenderServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finca.services.render.v1.Render/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenderServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Render_serviceDesc = grpc.ServiceDesc{
	ServiceName: "finca.services.render.v1.Render",
	HandlerType: (*RenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _Render_ListJobs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueueJob",
			Handler:       _Render_QueueJob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "git.underland.io/ehazlett/finca/api/services/render/v1/render.proto",
}
