kind: pipeline
type: kubernetes
name: default

workspace:
  path: /go/src/github.com/fynca/fynca

steps:
- name: test
  image: golang
  commands:
  - go -mod=mod test -v ./...

- name: build
  image: golang
  commands:
  - make
