kind: pipeline
type: kubernetes
name: default

workspace:
  base: /go
  path: src/github.com/fynca/fynca

steps:
- name: test
  image: golang
  commands:
  - make test
- name: build
  image: golang
  commands:
  - make
