GRPCAddress = "127.0.0.1:8080"
TLSServerCertificate = ""
TLSServerKey = ""
TLSClientCertificate = ""
TLSClientKey = ""
TLSInsecureSkipVerify = false
S3Endpoint = "s3.underland.io"
S3AccessID = "finca"
S3AccessKey = "c7752eff114aabc2562e3378a2f3a6eb"
S3Bucket = "finca"
S3UseSSL = true
NATSURL = "nats://127.0.0.1:4222"
NATSSubject = "JOBS"
JobTimeout = "8h"
JobOutputDir = "/tmp/finca-render"
JobPrefix = ""
JobPriority = 50
JobImage = "r.underland.io/apps/finca:latest"
JobMaxAttempts = 2
JobCPU = 1000
JobMemory = 1024
