version: "3.9"
services:
  redis:
    image: docker.io/library/redis:latest
    ports:
      - 6379:6379

  minio:
    image: docker.io/minio/minio:latest
    entrypoint: "/bin/bash"
    command: -c "mkdir -p /data/flow && minio server --console-address :9001 /data"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9000:9000
      - 9001:9001

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 7080:7080
    command: ["-D", "server", "-c", "/etc/flow.toml"]
    volumes:
      - ./flow-dev.toml:/etc/flow.toml
    depends_on:
      - minio
      - redis

  manager:
    image: docker.io/ehazlett/flow-manager:latest
    ports:
      - 9080:9080
    command: ["-a", "backend:7080", "-D", "-l", ":9080", "--api-cors-domain", '"*"']
    depends_on:
      - backend

