version: "3.9"
services:
  postgres:
    image: docker.io/library/postgres:14-alpine
    environment:
      - "POSTGRES_USER=flow"
      - "POSTGRES_PASSWORD=flow"
      - "POSTGRES_DB=flow"
    volumes:
      - ./hack/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flow"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  minio:
    image: docker.io/minio/minio:latest
    entrypoint: "/bin/bash"
    command: -c "mkdir -p /data/flow && minio server --console-address :9001 /data"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9000:9000
      - 9001:9001

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 7080:7080
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/flow.toml
        GRPCAddress = ":7080"
        S3Endpoint = "minio:9000"
        S3AccessID = "minioadmin"
        S3AccessKey = "minioadmin"
        S3Bucket = "flow"
        S3UseSSL = false
        DatastoreAddress = "postgres://flow:flow@postgres:5432/flow?sslmode=disable"
        InitialAdminPassword = "flow"
        [Authenticator]
          Name = "token"
        EOF
        flow -D server -c /etc/flow.toml
    command: ["-D", "server", "-c", "/etc/flow.toml"]
    depends_on:
      - minio
      - postgres
