GRPCAddress = ":7080"
TLSServerCertificate = ""
TLSServerKey = ""
TLSClientCertificate = ""
TLSClientKey = ""
TLSInsecureSkipVerify = false
#S3Endpoint = "s3.underland.io"
#S3AccessID = "fynca"
#S3AccessKey = "bb603090dc42ed061a1acb44112971c6"
#S3Bucket = "fynca-dev"
#S3UseSSL = true
S3Endpoint = "127.0.0.1:9000"
S3AccessID = "minioadmin"
S3AccessKey = "minioadmin"
S3Bucket = "fynca"
S3UseSSL = false
NATSURL = "nats://127.0.0.1:4222"
#NATSURL = "nats://nats.int:4222"
NATSJobStreamName = "JOBS"
NATSJobStatusStreamName = "STATUS"
NATSKVBucketNameWorkers = "fynca-workers"
NATSKVBucketWorkerControl = "fynca-worker-control"
DatabaseAddress = "redis://127.0.0.1:6379/0"
JobTimeout = "0h10m0s"
InitialAdminPassword = "fynca"
#TraceEndpoint = "127.0.0.1:4317"
Environment = "dev"
JobPrefix = ""
JobPriority = 50
JobCPU = 1000
JobMemory = 1024

[Authenticator]
  Name = "token"

[[Workers]]
  MaxJobs = 0
  [[Workers.RenderEngines]]
    Name = "blender"
    Path = "/opt/blender/blender"
