GRPCAddress = ":7080"
S3Endpoint = "minio.dev.fynca.io:9000"
S3AccessID = "minioadmin"
S3AccessKey = "minioadmin"
S3Bucket = "fynca"
S3UseSSL = false
NATSURL = "nats://nats:4222"
NATSJobStreamName = "JOBS"
NATSJobStatusStreamName = "STATUS"
NATSKVBucketWorkerControl = "fynca-worker-control"
DatabaseAddress = "redis://redis:6379/0"
JobTimeout = "1h0m0s"
InitialAdminPassword = "fynca"

[Authenticator]
  Name = "token"
